1.长期趋势变化  
2.季节性周期变化  
3.循环变化  
4.随机性变化

### 淘宝店铺三年增长趋势和季节性波动分析  
key：重采样函数resample()，对事件进行按频率采样  
w--周  
m--月末  
q--季度  
a--年末  
as--年初  
subplots()绘制多个子图，subplots_adjust()调节子图

In [7]:
import pandas as pd
import matplotlib.pyplot as plt
plt.rcParams['font.sans-serif'] = ['SimHei']

In [11]:
df = pd.read_excel("TaoBao.xlsx")
df.head()

,买家会员名,支付金额,宝贝总数量,宝贝标题,付款时间,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,mrkj0001,63.7,1,Java从入门到精通（第4版 附光盘）,2017-01-02 23:29:12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mrkj0002,268.0,1,【明日科技】编程词典C#个人版,2017-01-03 16:01:54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,mrkj0003,134.0,1,【明日科技】编程词典JavaWeb个人版,2017-01-03 16:59:49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mrkj0004,268.0,1,【明日科技】编程词典Java个人版,2017-01-03 16:59:49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mrkj0005,999.0,1,【正版-即插即用】Java编程词典珍藏版（含500G移动硬盘）明日,2017-01-04 15:07:49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df1 = df[["付款时间", "支付金额"]]
df1.head()

                  付款时间   支付金额
0  2017-01-02 23:29:12   63.7
1  2017-01-03 16:01:54  268.0
2  2017-01-03 16:59:49  134.0
3  2017-01-03 16:59:49  268.0
4  2017-01-04 15:07:49  999.0

In [39]:
df1['付款时间'] = pd.to_datetime(df['付款时间'], errors='coerce')
df1.head()

C:\Users\杜苏苏\AppData\Local\Temp\ipykernel_7440\3246821512.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['付款时间'] = pd.to_datetime(df['付款时间'], errors='coerce')

                 付款时间   支付金额
0 2017-01-02 23:29:12   63.7
1 2017-01-03 16:01:54  268.0
2 2017-01-03 16:59:49  134.0
3 2017-01-03 16:59:49  268.0
4 2017-01-04 15:07:49  999.0

In [41]:
df1.loc[:, '付款时间'] = pd.to_datetime(df['付款时间'], errors='coerce')
df1.head()

                 付款时间   支付金额
0 2017-01-02 23:29:12   63.7
1 2017-01-03 16:01:54  268.0
2 2017-01-03 16:59:49  134.0
3 2017-01-03 16:59:49  268.0
4 2017-01-04 15:07:49  999.0

In [49]:
df1 = df1.set_index('付款时间')

D:\Anaconda3\Lib\site-packages\pandas\core\indexes\base.py:7588: FutureWarning: Dtype inference on a pandas object (Series, Index, ExtensionArray) is deprecated. The Index constructor will keep the original dtype in the future. Call `infer_objects` on the result to get the old behavior.
  return Index(sequences[0], name=names)

In [43]:
# 按年统计
# resample('AS')：按照年度重采样（AS 代表“年初开始的采样”），并计算年度数据的总和。
# to_period('A')：将日期索引转换为年度周期格式。
df_y = df1.resample('AS').sum().to_period('A')
df_y

C:\Users\杜苏苏\AppData\Local\Temp\ipykernel_7440\4020675524.py:4: FutureWarning: 'AS' is deprecated and will be removed in a future version, please use 'YS' instead.
  df_y = df1.resample('AS').sum().to_period('A')

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'RangeIndex'

In [47]:
df = pd.read_excel("TaoBao.xlsx")
df1 = df[["付款时间", "支付金额"]]
df1.loc[:, '付款时间'] = pd.to_datetime(df['付款时间'], errors='coerce')
df1.set_index('付款时间')
df_y = df1.resample('AS').sum().to_period('A')

D:\Anaconda3\Lib\site-packages\pandas\core\indexes\base.py:7588: FutureWarning: Dtype inference on a pandas object (Series, Index, ExtensionArray) is deprecated. The Index constructor will keep the original dtype in the future. Call `infer_objects` on the result to get the old behavior.
  return Index(sequences[0], name=names)
C:\Users\杜苏苏\AppData\Local\Temp\ipykernel_7440\4293054467.py:5: FutureWarning: 'AS' is deprecated and will be removed in a future version, please use 'YS' instead.
  df_y = df1.resample('AS').sum().to_period('A')

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'RangeIndex'